# Generated by Django 4.2.1 on 2023-05-26 20:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adupload', '0002_document_pdf_title_alter_document_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='pdf_title', unique=True),
        ),
    ]
